dbt_BigQuery:
  outputs:
    dev:
      dataset: dbt_BigQuery
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "dbt_BigQuery/dbt-BigQuery.json"
      location: US
      method: service-account
      priority: interactive
      project: dbt-bigquery-rvm
      threads: 1
      type: bigquery
  target: dev
