dbt_bigquery_main:
  outputs:
    dev:
      dataset: dbt_bigquery_main
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "key-dbt-bq.json"
      location: US
      method: service-account
      priority: interactive
      project: dbt-bigquery-rvm
      threads: 1
      type: bigquery
  target: dev
